# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X3bS6xLLxEdU7OVlNpyU96mpcM7HJLEm
"""

def tashxis (belgi):
  if belgi == "istima":
     return "Parasetamol iching"
  elif belgi == "katarakta":
     return "deksamitazon"
  elif belgi == "bosh ogʻrigʻi":
     return "trimol"
  elif belgi == "gripp":
     return "taylol hot"
  else:
     return "Shifokorga murojaat qiling"
belgi=input("Kasallik belgisini kiriting")
natija=tashxis(belgi)
print(natija)

from google.colab.patches import cv2_imshow
import cv2
def TELEFON(iphone):
  if iphone == "Iphone X":
     rasm=cv2.imread("photo_5912280091243689817_x.jpg")
     cv2_imshow(rasm)
     return "150 $"
  elif iphone == "Iphone 11 Pro":
     rasm1=cv2.imread("photo_6011697211072689631_x.jpg")
     cv2_imshow(rasm1)
     return "250 $"
  elif iphone == "Iphone 12":
     rasm2=cv2.imread("photo_6004984701175051612_x.jpg")
     cv2_imshow(rasm2)
     return "300 $"
  elif iphone == "Iphone 12 Pro ":
     rasm3=cv2.imread("photo_5808661836269203128_w.jpg")
     cv2_imshow(rasm3)
     return "350 $"
  elif iphone == "Iphone 14 ":
     rasm4=cv2.imread("photo_5880636820906161288_w.jpg")
     cv2_imshow(rasm4)
     return "400 $"
  else:
     return "Telefon mavjud emas:"
iphone=input("Telefon nomini kiriting:")
natija=TELEFON(iphone)
print(natija)